config/routes.rb
Openplaques::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :new, :create]

  # This site is designed to be RESTful, so most of the routes are defined here as resources.

  # These ones are related to plaques, but only in general, not a single plaque, and so use plaques as a prefix in the path. These have to be defined BEFORE the plaques resource.
  scope "/plaques" do
    resources :erected_in, :controller => :plaque_erected_years, :as => :plaque_erected_years, :only => [:index, :show]
    resource :latest, :as => :latest, :controller => :plaques_latest, :only => :show
  end

  resources :plaques do
    member do
      post 'parse_inscription'
      post 'unparse_inscription'
      post 'flickr_search'
      post 'flickr_search_all'
    end
    resource :location, :controller => :plaque_location, :only => :edit
    resource :erected, :controller => :plaque_erected, :only => :edit
    resource :colour, :controller => :plaque_colour, :only => :edit
    resource :geolocation, :controller => :plaque_geolocation, :only => :edit
    resource :inscription, :controller => :plaque_inscription, :only => :edit
    resource :description, :controller => :plaque_description, :only => [:edit, :show]
    resource :language, :controller => :plaque_language, :only => :edit
    resources :connections, :controller => "PersonalConnections", :as => :connections
    resource :photos, :controller => :plaque_photos, :only => :show
    resource :talk, :controller => :plaque_talk, :only => :create
    resources :sponsorships
  end
  # map tiles are numbered using the convention at http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
  match 'plaques/tiles/:zoom/:x/:y' => 'plaques#index', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  match 'plaques/unphotographed/tiles/:zoom/:x/:y' => 'plaques#index', :id => 'unphotographed', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }

  resources :places, :controller => :countries, :as => :countries do
    resources :plaques, :controller => :country_plaques, :only => :show
    resources :areas do
      resource :plaques, :controller => :area_plaques, :only => :show
      resource :unphotographed, :controller => :area_plaques, :id => 'unphotographed', :only => :show
#      resource :ungeolocated, :controller => :area_plaques, :id => 'ungeolocated', :only => :show
    end
  end
  resources :locations, :only => [:show, :edit, :update, :destroy]
  resources :areas, :controller => :all_areas, :only => :show
  resource :areas, :controller => :all_areas, :only => :show

  resources :photos
  resources :photographers, :as => :photographers, :only => [:create, :index, :show, :new]
  resources :licences, :only => [:index, :show]

  resources :organisations do
    resource :plaques, :controller => :organisation_plaques, :only => :show
    match 'plaques/tiles/:zoom/:x/:y' => 'organisation_plaques#show', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  end
  resources :sponsorships

  resources :verbs

  scope "/roles" do
    resources "a-z", :controller => :roles_by_index, :as => "roles_by_index", :only => [:show, :index]
  end
  resources :roles
  resources :personal_roles

  scope "/people" do
    resources "a-z", :controller => :people_by_index, :as => "people_by_index", :only => :show
    resources :born_on, :controller => :people_born_on, :as => "people_born_on", :only => [:index, :show]
    resources :died_on, :controller => :people_died_on, :as => "people_died_on", :only => [:index, :show]
    resources :born_in, :controller => :people_born_on, :as => "people_born_in", :only => [:index, :show]
    resources :died_in, :controller => :people_died_on, :as => "people_died_in", :only => [:index, :show]
    resources :alive_in, :controller => :people_alive_in, :as => "people_alive_in", :only => [:index, :show]
  end
  resources :people do
    resource :plaques, :controller => :person_plaques, :only => :show
    resource :roles, :controller => :person_roles, :only => :show
  end

  resources :languages
  resources :colours
  resources :series
  resources :todo
  resources :picks

  # Convenience paths for search:
  match 'search' => "search#index"
  match 'search/:phrase' => "search#index"
  match 'match' => "match#index"

  # Convenience resources for important pages:
  resources :pages
  resource :about, :controller => :pages, :id => "about", :only => :show
  resource :contact, :controller => :pages, :id => "contact", :only => :show
  scope "/about" do
    resource :data, :controller => :pages, :id => "data", :as => "about_the_data", :only => :show
  end
  resource :contribute, :controller => :pages, :id => "contribute", :as => "contribute", :only => :show
  resource :explore, :controller => :explore, :only => :show

  # Convenience paths for login/logout/register:
  match 'logout' => 'sesssions#destroy', :as => :logout
  match 'login' => 'sesssions#new', :as => :login
  match 'register' => 'users#new', :as => :register

  # The Homepage
  root :to => "homepage#index"

  match '*path', :to => 'errors#not_found'

end

app/models/personal_connection.rb
# This class represents a commemoration of a Person on a commemorative Plaque, and acts as a
# convenient 'join' between the two.
# === Associations
# * Plaque - the plaque on which this commemoration occurs.
# * Person - the person referenced in the commemoration
# * Location - the location referenced in the commemoration (usually the same location as where the plaque is physically located, but this can be different in the case of plaques which commemorate a 'nearby' site or event.).
# * Verb - the verb used to describe the association (eg 'lived').
class PersonalConnection < ActiveRecord::Base

  validates_presence_of :verb_id, :person_id, :location_id, :plaque_id

  belongs_to :verb, :counter_cache => true
  belongs_to :person, :counter_cache => true
  belongs_to :location, :counter_cache => true
  belongs_to :plaque, :counter_cache => true

  attr_accessor :other_verb_id

  def from
    if (verb.id == 8 or verb.id == 504)
      return person.born_in.to_s
    end
    if (verb.id == 3 or verb.id == 49 or verb.id == 161 or verb.id == 288 or verb.id == 566 or verb.id == 1108)
      return person.died_in.to_s
    end
    started_at ? started_at.year.to_s : ""
  end

  def to
    if (verb.id == 8 or verb.id == 504)
      return person.born_in.to_s
    end
    if (verb.id == 3 or verb.id == 49 or verb.id == 161 or verb.id == 288 or verb.id == 566 or verb.id == 1108)
      return person.died_in.to_s
    end
    ended_at ? ended_at.year.to_s : ""
  end

end

app/controllers/personal_connections_controller.rb
class PersonalConnectionsController < ApplicationController

  before_filter :authenticate_admin!, :only => :destroy

  before_filter :find_plaque, :only => [:edit, :update, :new, :create]
  before_filter :find_personal_connection, :only => [:edit, :destroy]
  before_filter :list_people_and_verbs, :only => [:new, :edit]

  def destroy
    @personal_connection.destroy
    redirect_to :back
  end

  def edit
    @locations = Location.all(:order => :name)
  end

  def update
    @personal_connection = @plaque.personal_connections.find(params[:id])
    if params[:personal_connection][:started_at] > ""
      started_at = params[:personal_connection][:started_at]
      if started_at =~/\d{4}/
        started_at = started_at + "-01-01"
        started_at = Date.parse(started_at)
        @personal_connection.started_at = started_at
      end
    end
    if params[:personal_connection][:ended_at] > ""
      ended_at = params[:personal_connection][:ended_at]
      if ended_at =~/\d{4}/
        ended_at = ended_at + "-01-01"
        ended_at = Date.parse(ended_at)
        @personal_connection.ended_at = ended_at
      end
    end
    if @personal_connection.update_attributes(params[:personal_connection])
      redirect_to edit_plaque_path(@plaque.id)
    else
      render :edit
    end
  end

  def new
    @personal_connection = @plaque.personal_connections.new
  end

  def create
    @personal_connection = @plaque.personal_connections.new(params[:personal_connection])
    if params[:personal_connection][:started_at] > ""
      started_at = params[:personal_connection][:started_at]
      if started_at =~/\d{4}/
        started_at = started_at + "-01-01"
        started_at = Date.parse(started_at)
        @personal_connection.started_at = started_at
      end
    end
    if params[:personal_connection][:ended_at] > ""
      ended_at = params[:personal_connection][:ended_at]
      if ended_at =~/\d{4}/
        ended_at = ended_at + "-01-01"
        ended_at = Date.parse(ended_at)
        @personal_connection.ended_at = ended_at
      end
    end
    if @personal_connection.save
      redirect_to :back
    else
      # can we just redirect to new?
      list_people_and_verbs
      render :new
    end
  end

  protected

    def find_plaque
      @plaque = Plaque.find(params[:plaque_id])
    end

    def find_personal_connection
      @personal_connection = PersonalConnection.find(params[:id])
    end
    
    def list_people_and_verbs
      @people = Person.all(:order => :name, :select => 'id, name, born_on, died_on')
      @verbs = Verb.all(:order => :name, :select => 'id, name' )
      @common_verbs = Verb.common
    end

end

app/views/personal_connections/_personal_connection.html.erb
<div class="inside_panel">
  Open Plaques conclude that <%= render personal_connection.person %>
  <strong><%= personal_connection.verb.name %></strong> at 
  <%= render personal_connection.location if personal_connection.location %> from the plaque:
  <div class="inside_panel"><%= render "plaques/minimal", :plaque => personal_connection.plaque if personal_connection.plaque %></div>
</div>

app/views/personal_connections/edit.html.erb
<div class="panel">
  <h1>Edit connection for <%= link_to @plaque.title, @plaque %></h1>
  
  <p>From <%= render 'plaques/minimal', :plaque => @plaque %> we can establish that</p>

  <%= form_for @personal_connection, :url => plaque_connection_path(@plaque, @personal_connection) do |f| %>
    <p>
      <%= f.collection_select :person_id, @people, :id, :name_and_dates %>
      <%= link_to("Add person", new_person_path) %>
    </p>
    <p>
      <%= f.collection_select :verb_id, @verbs, :id, :name %>
      <%= link_to("Add verb", new_verb_path) %>
    </p>
    <p>
      <%= f.label :location_id, "At" %>
      <%= f.collection_select :location_id, @locations, :id, :name %>
    </p>
    <p>
      <%= f.label :started_at, "From" %>
      <%= f.text_field :started_at %>
    </p>
    <p>
      <%= f.label :ended_at, "To" %>
      <%= f.text_field :ended_at %>
    </p>
    <%= f.submit "Update", :class => :button %>
  <% end %>
</div>

app/views/personal_connections/new.html.erb
<% content_for :page_title, "Edit connections for plaque \#" + @plaque.id.to_s %>

<%= render 'plaques/edit_bar', :plaque => @plaque %>

<div class="panel">
  <h1>Connections for the <%= link_to @plaque.title, @plaque %></h1>
  <p>From <%= render 'plaques/minimal', :plaque => @plaque %> we can establish that</p>
  <ul><% @plaque.personal_connections.all.each do |pc| %><li><%= link_to pc.person.name, person_path(pc.person) if pc.person %> <%= pc.verb.name if pc.verb %>
    <%= "at " + pc.location.full_address if pc.location %>
    <%= "from " + pc.started_at.year.to_s if pc.started_at %><%= " to " + pc.ended_at.year.to_s if pc.ended_at %> 
    <%= link_to "Edit", edit_personal_connection_path(pc) %> <%= button_to("Delete", personal_connection_path(pc), :method => :delete, :class => :button)%> </li>
  <% end %>
  <% if @plaque.personal_connections.size == 0 %>
    <li>No facts have been established yet</li>
  <% end %>
  </ul>
  <%= form_for @personal_connection, :url => personal_connections_path(@plaque) do |f| %>
    <fieldset>
      <div class="row">
        <%= f.collection_select :person_id, @people, :id, :name_and_dates, {} , { "style" => "width:400px" } %> <%= link_to("Add person", "/people/new") %>
      </div>
      <div class="row">
        <%= f.collection_select :verb_id, @verbs, :id, :name, { :selected => "222"}, { "style" => "width:400px" } %>  <%= link_to("Add verb", "/verbs/new") %>
      </div>
      <% if @plaque.location %>
        <div class="row">at <%= @plaque.location.full_address %><%= f.hidden_field :location_id, :value => @plaque.location.id %></div>
      <% else %>
        <div class="row">There is no location for this plaque. Probably shouldn't create a connection.</div>
      <% end %>
      <div class="row">
        <%= f.label :started_at, "From" %>
        <%= f.text_field :started_at %>
      </div>
      <div class="row">
        <%= f.label :ended_at, "To" %>
        <%= f.text_field :ended_at %>
      </div>
    </fieldset>
    <%= f.submit "Add", :class => :button %>
  <% end %>
</div>