config/routes.rb
Openplaques::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :new, :create]

  # This site is designed to be RESTful, so most of the routes are defined here as resources.

  # These ones are related to plaques, but only in general, not a single plaque, and so use plaques as a prefix in the path. These have to be defined BEFORE the plaques resource.
  scope "/plaques" do
    resources :erected_in, :controller => :plaque_erected_years, :as => :plaque_erected_years, :only => [:index, :show]
    resource :latest, :as => :latest, :controller => :plaques_latest, :only => :show
  end

  resources :plaques do
    member do
      post 'parse_inscription'
      post 'unparse_inscription'
      post 'flickr_search'
      post 'flickr_search_all'
    end
    resource :location, :controller => :plaque_location, :only => :edit
    resource :erected, :controller => :plaque_erected, :only => :edit
    resource :colour, :controller => :plaque_colour, :only => :edit
    resource :geolocation, :controller => :plaque_geolocation, :only => :edit
    resource :inscription, :controller => :plaque_inscription, :only => :edit
    resource :description, :controller => :plaque_description, :only => [:edit, :show]
    resource :language, :controller => :plaque_language, :only => :edit
    resources :connections, :controller => "PersonalConnections", :as => :connections
    resource :photos, :controller => :plaque_photos, :only => :show
    resource :talk, :controller => :plaque_talk, :only => :create
    resources :sponsorships
  end
  # map tiles are numbered using the convention at http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
  match 'plaques/tiles/:zoom/:x/:y' => 'plaques#index', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  match 'plaques/unphotographed/tiles/:zoom/:x/:y' => 'plaques#index', :id => 'unphotographed', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }

  resources :places, :controller => :countries, :as => :countries do
    resources :plaques, :controller => :country_plaques, :only => :show
    resources :areas do
      resource :plaques, :controller => :area_plaques, :only => :show
      resource :unphotographed, :controller => :area_plaques, :id => 'unphotographed', :only => :show
#      resource :ungeolocated, :controller => :area_plaques, :id => 'ungeolocated', :only => :show
    end
  end
  resources :locations, :only => [:show, :edit, :update, :destroy]
  resources :areas, :controller => :all_areas, :only => :show
  resource :areas, :controller => :all_areas, :only => :show

  resources :photos
  resources :photographers, :as => :photographers, :only => [:create, :index, :show, :new]
  resources :licences, :only => [:index, :show]

  resources :organisations do
    resource :plaques, :controller => :organisation_plaques, :only => :show
    match 'plaques/tiles/:zoom/:x/:y' => 'organisation_plaques#show', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  end
  resources :sponsorships

  resources :verbs

  scope "/roles" do
    resources "a-z", :controller => :roles_by_index, :as => "roles_by_index", :only => [:show, :index]
  end
  resources :roles
  resources :personal_roles

  scope "/people" do
    resources "a-z", :controller => :people_by_index, :as => "people_by_index", :only => :show
    resources :born_on, :controller => :people_born_on, :as => "people_born_on", :only => [:index, :show]
    resources :died_on, :controller => :people_died_on, :as => "people_died_on", :only => [:index, :show]
    resources :born_in, :controller => :people_born_on, :as => "people_born_in", :only => [:index, :show]
    resources :died_in, :controller => :people_died_on, :as => "people_died_in", :only => [:index, :show]
    resources :alive_in, :controller => :people_alive_in, :as => "people_alive_in", :only => [:index, :show]
  end
  resources :people do
    resource :plaques, :controller => :person_plaques, :only => :show
    resource :roles, :controller => :person_roles, :only => :show
  end

  resources :languages
  resources :colours
  resources :series
  resources :todo
  resources :picks

  # Convenience paths for search:
  match 'search' => "search#index"
  match 'search/:phrase' => "search#index"
  match 'match' => "match#index"

  # Convenience resources for important pages:
  resources :pages
  resource :about, :controller => :pages, :id => "about", :only => :show
  resource :contact, :controller => :pages, :id => "contact", :only => :show
  scope "/about" do
    resource :data, :controller => :pages, :id => "data", :as => "about_the_data", :only => :show
  end
  resource :contribute, :controller => :pages, :id => "contribute", :as => "contribute", :only => :show
  resource :explore, :controller => :explore, :only => :show

  # Convenience paths for login/logout/register:
  match 'logout' => 'sesssions#destroy', :as => :logout
  match 'login' => 'sesssions#new', :as => :login
  match 'register' => 'users#new', :as => :register

  # The Homepage
  root :to => "homepage#index"

  match '*path', :to => 'errors#not_found'

end

app/helpers/plaques_helper.rb
require 'open-uri'
require 'net/http'
require 'uri'
require 'rexml/document'

module PlaquesHelper

  def marked_text(text, term)
    text.to_s.gsub(/(#{term})/i, '<mark>\1</mark>').html_safe
  end

  def search_snippet(text, search_term)
    regex = /#{search_term}/i
    if text =~ regex
      text = " " + text + " "  #HACK: This is so there's a space before the first word.
      indexes = []
      first_index = text.index(regex)
      indexes << first_index
      second_index = text.index(regex, (first_index + search_term.length + 50))
      indexes << second_index if second_index
      snippet = ""
      indexes.each do |i|
        i = i - 80
        i = 0 if i < 0
        s = text[i, 160]
        first_space = (s.index(/\s/) + 1)
        last_space = (s.rindex(/\s/) - 1)
        snippet += "..." if i > 0
        snippet += (s[first_space..last_space])
        snippet += "..." if last_space + 2 < text.length
      end
      snippet
    else
      return text
    end
  end

  def kml(plaque, xml)
    if plaque.geolocated?
      xml.Placemark do
        xml.name(plaque.title)
        xml.description do
          xml.cdata!(("<p>" + plaque.inscription + "</p> <p><a href=\"" + plaque_url(plaque) + "\">" + thumbnail_img(plaque) + "</a></p>").html_safe)
        end
        if plaque.latitude && plaque.longitude
          xml.Point do
            xml.coordinates plaque.longitude.to_s + ',' + plaque.latitude.to_s + ",0"
          end
        end
        if plaque.colour && plaque.colour.slug =~ /(blue|black|yellow|red|white|green)/
          xml.styleUrl "#plaque-" + plaque.colour.slug
        else
          xml.styleUrl "#plaque-blue"
        end
      end
    end
  end

  # pass null to search all machinetagged photos on Flickr
  def find_photo_by_machinetag(plaque, flickr_user_id)
#    key = FLICKR_KEY # "86c115028094a06ed5cd19cfe72e8f8b"
    key = "86c115028094a06ed5cd19cfe72e8f8b"
    content_type = "1" # Photos only
    machine_tag_key = "openplaques:id=".to_s
    if (plaque)
      machine_tag_key += plaque.id.to_s
    end

    flickr_url = "https://api.flickr.com/services/rest/"
    method = "flickr.photos.search"
    license = "1,2,3,4,5,6,7" # All the CC licencses that allow commercial re-use

    20.times do |page|

      url = flickr_url + "?api_key=" + key + "&method=" + method + "&page=" + page.to_s + "&license=" + license + "&content_type=" + content_type + "&machine_tags=" + machine_tag_key +  "&extras=date_taken,owner_name,license,geo,machine_tags"

      if (flickr_user_id)
        url += "&user_id=" + flickr_user_id
      end
      puts url

      new_photos_count = 0
      response = open(url)
      doc = REXML::Document.new(response.read)
      doc.elements.each('//rsp/photos/photo') do |photo|
        print "."
        $stdout.flush

        @photo = nil

        file_url = "http://farm" + photo.attributes["farm"] + ".staticflickr.com/" + photo.attributes["server"] + "/" + photo.attributes["id"] + "_" + photo.attributes["secret"] + "_z.jpg"
        photo_url = "http://www.flickr.com/photos/" + photo.attributes["owner"] + "/" + photo.attributes["id"] + "/"

        @photo = Photo.find_by_url(photo_url)

        if @photo
        else
          plaque_id = photo.attributes["machine_tags"][/openplaques\:id\=(\d+)/, 1]

          puts photo.attributes["title"]

          @plaque = Plaque.find(:first, :conditions => {:id => plaque_id})
          if @plaque
            @photo = Photo.new
            @photo.plaque = @plaque
            @photo.file_url = file_url
            @photo.url = photo_url
            @photo.taken_at = photo.attributes["datetaken"]
            @photo.photographer_url = photo_url = "http://www.flickr.com/photos/" + photo.attributes["owner"] + "/"
            @photo.photographer = photo.attributes["ownername"]
            if photo.attributes["license"] == "4"
              @photo.licence = Licence.find_by_url("http://creativecommons.org/licenses/by/2.0/")
            elsif photo.attributes["license"] == "6"
              @photo.licence = Licence.find_by_url("http://creativecommons.org/licenses/by-nd/2.0/")
            elsif photo.attributes["license"] == "3"
              @photo.licence = Licence.find_by_url("http://creativecommons.org/licenses/by-nc-nd/2.0/")
            elsif photo.attributes["license"] == "2"
              @photo.licence = Licence.find_by_url("http://creativecommons.org/licenses/by-nc/2.0/")
            elsif photo.attributes["license"] == "1"
              @photo.licence = Licence.find_by_url("http://creativecommons.org/licenses/by-nc-sa/2.0/")
            elsif photo.attributes["license"] == "5"
              @photo.licence = Licence.find_by_url("http://creativecommons.org/licenses/by-sa/2.0/")
            elsif photo.attributes["license"] == "7"
              @photo.licence = Licence.find_by_url("http://www.flickr.com/commons/usage/")
            elsif photo.attributes["license"] == "0"
              @photo.licence = Licence.find_by_url("http://en.wikipedia.org/wiki/All_rights_reserved/")
            else
              puts "Couldn't find license"
            end
            if @photo.save
              new_photos_count += 1
              puts "New photo found and saved"
            else
#            puts "Error saving photo" + @photo.errors.each_full{|msg| puts msg }
            end

            if photo.attributes["latitude"] != "0" && photo.attributes["longitude"] != "0" && !@plaque.geolocated?
              puts "New geolocation found"
              @plaque.latitude = photo.attributes["latitude"]
              @plaque.longitude = photo.attributes["longitude"]
              if @plaque.save
                puts "New geolocation added to photo"
              else
                puts "Error adding geolocation to photo" + plaque.errors.full_messages.to_s #methods.join(" ")
              end
            end
          else
            puts "Photo's machine tag doesn't match a plaque."
          end
        end
      end
    end
  end

    # pass null to search all photos on Flickr
    def crawl_flickr(group_id='74191472@N00')
    
      key = "86c115028094a06ed5cd19cfe72e8f8b" # FLICKR_KEY
      content_type = "1" # Photos only
      flickr_url = "https://api.flickr.com/services/rest/"
      method = "flickr.photos.search"
      jez = User.find(2)
      black = Colour.find_by_name('black')
      english = Language.find_by_name('English')
      new_photos_count = 0
            
      19.times do |page|
        puts page.to_s
        url = flickr_url + "?api_key=" + key + "&method=" + method + "&page=" + page.to_s + "&per_page=5&content_type=" + content_type + "&extras=date_taken,owner_name,license,geo,description"
        if group_id
          url += "&group_id=" + group_id
        end
        response = open(url)
        doc = REXML::Document.new(response.read)
        doc.elements.each('//rsp/photos/photo') do |photo|
          print "."
          $stdout.flush
          @photo = nil
          file_url = "http://farm" + photo.attributes["farm"] + ".staticflickr.com/" + photo.attributes["server"] + "/" + photo.attributes["id"] + "_" + photo.attributes["secret"] + "_z.jpg"
          photo_url = "http://www.flickr.com/photos/" + photo.attributes["owner"] + "/" + photo.attributes["id"] + "/"
          @photo = Photo.find_by_url(photo_url)
          inscription_is_stub = true
          if photo.attributes["title"]!=nil
            subject = photo.attributes["title"].split(",")[0].split("()")[0].rstrip.lstrip + "."
            inscription = subject
          end
          if photo.elements["description"].text != nil && photo.elements["description"].text.length > 50
            inscription << " " + photo.elements["description"].text
          end
          if @photo
            puts "photo already exists in Open Plaques"
          else
            # Plaque find by location and name if already exists.....
#            32.76696, -94.348526
#            32.766955, -94.348472
            # Plaque.find_or_create_by_???
            @plaque = Plaque.new(:inscription => inscription, :user => jez, :inscription_is_stub => inscription_is_stub, :colour => black, :language => english)
            @plaque.location = Location.new(:name => 'somewhere in Texas')
            # the Flickr woeids appear to be at town level, so can only create an area from them
            woeid = photo.attributes["woeid"]
            if woeid != nil
              area = Area.find_or_create_by_woeid(woeid)
              if area != nil
                @plaque.location.area = area
              else
                puts "error: provided woeid " + woeid + " but got no area back"
              end
            end
            if @plaque
              @photo = Photo.new
              @photo.plaque = @plaque
              @photo.file_url = file_url
              @photo.url = photo_url
              @photo.taken_at = photo.attributes["datetaken"]
              @photo.photographer_url = photo_url = "http://www.flickr.com/photos/" + photo.attributes["owner"] + "/"
              @photo.photographer = photo.attributes["ownername"]
              @photo.licence = Licence.find_by_flickr_licence_id(photo.attributes["license"])
              if photo.attributes["latitude"] != "0" && photo.attributes["longitude"] != "0" && !@plaque.geolocated?
                @plaque.latitude = photo.attributes["latitude"]
                @plaque.longitude = photo.attributes["longitude"]
              end
              if @plaque.save
                puts "New plaque and photo added"
              else
                puts "Error adding plaque " + @plaque.errors.full_messages.to_s
              end
              if @photo.save
                puts "New photo found and saved"
              else
                puts "Error saving photo" + @photo.errors.each_full{|msg| puts msg }
              end
            end
          end
        end
      end
    end

  def poi(plaque)
    if plaque.geolocated? && plaque.people.size() > 0

app/views/plaques/_contributor_details.erb
<aside>
  <h2>Contributor details</h2>
  <ul>
    <li><p>Inscription added by <a href="#">Simon Harriyott</a></p></li>
    <li><p>Photographs added by <a href="#">Simon Harriyott</a>, <a href="#">Frankie Roberto</a> &amp; <a href="#">myf</a></p></li>
    <li><p>Further edits contributed from <a href="#">Jez Nicholson</a></p></li>
  </ul>
</aside>

app/views/plaques/_details.erb
<table class="section_details" cellspacing="0" summary="Plaque details for #<%= plaque.id %>">
  <% if !plaque.is_accurate_geolocation %>
    <tr>
      <th>Map accuracy</th>
      <td>This is an approximate position</td>
    </tr>
  <% end %>
  <tr>
    <th><% if plaque.erected? %>Erected<% else %>To be erected<% end %></th>
    <td>
      <%= erected_information plaque %>
      <% if plaque.series %>as <% if plaque.series_ref? %>#<%= content_tag(:span, plaque.series_ref )%><% else %>part<% end %> of the <%= link_to plaque.series.name, plaque.series %> series<% end %>
    </td>
  </tr>
  <tr>
    <th>Language</th>
    <td><%= render plaque.language %></td>
  </tr>
  <tr>
    <th>Colour</th>
    <td>
      <%= render plaque.colour if plaque.colour %>
	    <% if !plaque.colour %>
        <% @colours = Colour.find(:all) %>
        <%= form_for plaque do |f| %>
          <%= f.label :colour_id, "This plaque is" %>
          <%= f.collection_select :colour_id, @colours, :id, :name, {:include_blank => true} %>
          <%= f.submit "Save", :class => :button %>
        <% end %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>Location</th>
    <td><%= render plaque.location if plaque.location %><br/><% if !plaque.geolocated? && current_user && current_user.is_admin? %>
	     [<%= link_to "geolocate this address", edit_plaque_geolocation_path(plaque), {:class => :edit, :title => "Geolocate"} %>]
	   <% end %>
	  </td>
  </tr>
  <tr>
    <th><%= pluralize_word(plaque.people.size, "Subject") %></th>
    <td>
      <%= render plaque.people %>
      <%= 'None identified yet' if plaque.people.size == 0 %>
    </td>
  </tr>
  <tr>
    <th>Machine tag</th>
    <td><%= plaque.machine_tag %></td>
  </tr>
  <% if !plaque.is_current %>
    <tr>
      <th>Not found</th>
      <td>As far as we know, it is not currently on display</td>
    </tr>
  <% end %>
  <% if !plaque.see_also.empty? %>
    <tr>
      <th>See also...</th>
      <td><%= render partial: 'plaques/tile', collection: plaque.see_also, as: :plaque %></td>
    </tr>
  <% end %>   
</table>

app/views/plaques/_edit_bar.html.erb
<% if current_user && current_user.is_admin? %>
  <section class="admin_panel">
    <%= link_to "Edit inscription", edit_plaque_inscription_path(plaque), {:class => :edit, :title => "Edit inscription"} %>

    <%= link_to "Establish connections", new_personal_connection_path(plaque), {:class => :edit, :title => "Establish connections"} %>

    <%= link_to "Establish sponsors", new_sponsorship_path(plaque), {:class => :edit, :title => "Establish sponsors"} %>

    <%= link_to "Edit description", edit_plaque_description_path(plaque), {:class => :edit, :title => "Edit description"} %>

    <%= link_to "Edit colour", edit_plaque_colour_path(plaque), {:class => :edit, :title => "Edit colour"} %>

    <%= link_to "Edit geolocation", edit_plaque_geolocation_path(plaque), {:class => :edit, :title => "Edit geolocation"} %>

    <%= link_to "Edit location", edit_location_path(plaque.location), {:class => :edit, :title => "Edit location"} %>

    <%= link_to "Edit erected date", edit_plaque_erected_path(plaque), {:class => :edit, :title => "Edit organisation"} %>

    <%= link_to "Show photos", plaque_photos_path(plaque), {:class => :show, :title => "Show photos"} %>
  </section>
<% end %>

app/views/plaques/_header.erb
<div class="header clearfix">
   <h1>Plaque <abbr title="number">№</abbr> <%= @plaque.id %></h1>

   <div class="like_button">
     <iframe src="http://www.facebook.com/plugins/like.php?href=<%= plaque_path(@plaque, :only_path => false) %>&amp;layout=button_count&amp;show_faces=false&amp;width=90&amp;action=like&amp;font&amp;colorscheme=light&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:20px; text-align:right;" allowTransparency="true"></iframe>
   </div>

</div>

app/views/plaques/_map.html.erb
<% @geolocated_plaques = @plaques.clone() if @plaques

if @geolocated_plaques

@geolocated_plaques.delete_if{ |plaque| !plaque.geolocated?} %>

<% if @geolocated_plaques != nil && @geolocated_plaques.length > 0 %>

  <% @center = find_mean(@geolocated_plaques) %>
    <style type="text/css">
        .olControlAttribution { bottom: 0px!important }
        #map {
            height: 512px;
        }
    </style>
    <script src="http://openlayers.org/api/OpenLayers.js"></script>
    <script type="text/javascript">

    // for different styles see http://openlayers.org/dev/examples/popupMatrix.html
        AutoSizeFramedCloud = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
            'autoSize': true
        });
        FramedCloudMinSize = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
            'autoSize': true,
            'minSize': new OpenLayers.Size(350,360)
        });

        var map, layer, markers, popup, currentPopup;
        var popupClass = AutoSizeFramedCloud;
        var size = new OpenLayers.Size(10,10);
        var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
        var icon = new OpenLayers.Icon('<%= asset_path 'openplaques-icon.png' %>',size,offset);
        var icon_blue = new OpenLayers.Icon('<%= asset_path 'icon-blue.png' %>',size,offset);
        var icon_black = new OpenLayers.Icon('<%= asset_path 'icon-black.png' %>',size,offset);
        var icon_green = new OpenLayers.Icon('<%= asset_path 'icon-green.png' %>',size,offset);
        var icon_red = new OpenLayers.Icon('<%= asset_path 'icon-red.png' %>',size,offset);
        var icon_white = new OpenLayers.Icon('<%= asset_path 'icon-white.png' %>',size,offset);
        var icon_yellow = new OpenLayers.Icon('<%= asset_path 'icon-yellow.png' %>',size,offset);
        <% if @centre %>
          var lat = <%= @centre.latitude %>;
          var lon = <%= @centre.longitude %>;
        <% else %>
          var lat = 0;
          var lon = 51.475;
        <%end %>
        <% if @zoom %>
          var zoom = <%= @zoom %>;
        <% else %>
          var zoom = 11;
        <% end %>

        // avoid pink tiles
        OpenLayers.IMAGE_RELOAD_ATTEMPTS = 3;
        OpenLayers.Util.onImageLoadErrorColor = "transparent";

        function init(){
            var options = {
                projection: new OpenLayers.Projection("EPSG:900913"),
                displayProjection: new OpenLayers.Projection("EPSG:4326"),
                units: "m",
                numZoomLevels: 18,
                maxResolution: 156543.0339,
                maxExtent: new OpenLayers.Bounds(-20037508, -20037508,
                                                 20037508, 20037508.34)
            };
            map = new OpenLayers.Map('map', options);
            layer = new OpenLayers.Layer.OSM();
            markers = new OpenLayers.Layer.Markers("Markers");
            map.addLayers([layer, markers]);

            var proj = new OpenLayers.Projection("EPSG:4326");
            var point = new OpenLayers.LonLat(lon, lat);
            point.transform(proj, map.getProjectionObject());

            map.setCenter(point, zoom);

            if (!map.getCenter()) {map.zoomToMaxExtent()}

           var popupContentHTML;

           <% for plaque in @geolocated_plaques %>
             <% if plaque.geolocated? %>
               popupClass = AutoSizeFramedCloud;
               point = new OpenLayers.LonLat(<%= plaque.longitude%>, <%= plaque.latitude%>);
               point.transform(proj, map.getProjectionObject());
               popupContentHTML = '<p><%= link_to("\#" + plaque.id.to_s, plaque) %> <%= html_safe(plaque.inscription) %> </p>';
               popupContentHTML = popupContentHTML + '<div class="popup_photo">';
               <% if plaque.photographed? %>
                 popupClass = FramedCloudMinSize;
                 <% photo = plaque.photos.first %>
                 <% if !photo.nil? %>
                   popupContentHTML = popupContentHTML + '<p><%= link_to(thumbnail_img(photo), plaque) %></p>';
                   popupContentHTML = popupContentHTML + '<p>Photographer: <%= link_to(html_safe(photo.photographer), photo.url) %>';
                   <% if !photo.licence.nil? %>
                     popupContentHTML = popupContentHTML + '<br/>License:&#160;<%= link_to(photo.licence.name, photo.licence.url)  %></p>';
                   <% end %>
                 <% end %>
               <% end %>
               popupContentHTML = popupContentHTML + '</div>';
               addMarker(point, <% if plaque.colour && plaque.colour.name =~ /(blue|black|yellow|red|white|green)/ %> '<%= plaque.colour.name %>' <% else %> 'blue' <% end %>, popupClass, popupContentHTML, true, true);
             <% end %>
           <% end %>
        }

        /**
         * Function: addMarker
         * Add a new marker to the markers layer given the following lonlat,
         *     popupClass, and popup contents HTML. Also allow specifying
         *     whether or not to give the popup a close box.
         *
         * Parameters:
         * ll - {<OpenLayers.LonLat>} Where to place the marker
         * popupClass - {<OpenLayers.Class>} Which class of popup to bring up
         *     when the marker is clicked.
         * popupContentHTML - {String} What to put in the popup
         * closeBox - {Boolean} Should popup have a close box?
         * overflow - {Boolean} Let the popup overflow scrollbars?
         */
        function addMarker(point, colour, popupClass, popupContentHTML, closeBox, overflow) {

            var feature = new OpenLayers.Feature(markers, point);
            feature.closeBox = closeBox;
            feature.popupClass = popupClass;
            feature.data.popupContentHTML = popupContentHTML;
            feature.data.overflow = (overflow) ? "auto" : "hidden";

            var marker = null;

            if (colour=="blue") {
              marker = new OpenLayers.Marker(point, icon_blue.clone());
            } else if (colour=="black") {
              marker = new OpenLayers.Marker(point, icon_black.clone());
            } else if (colour=="yellow") {
              marker = new OpenLayers.Marker(point, icon_yellow.clone());
            } else if (colour=="red") {
              marker = new OpenLayers.Marker(point, icon_red.clone());
            } else if (colour=="white") {
              marker = new OpenLayers.Marker(point, icon_white.clone());
            } else if (colour=="green") {
              marker = new OpenLayers.Marker(point, icon_green.clone());
            } else {
              marker = new OpenLayers.Marker(point, icon_blue.clone());
            }

            var markerClick = function (evt) {
                if (currentPopup != null) {
                  currentPopup.hide();
                }
                if (this.popup == null) {
                    this.popup = this.createPopup(this.closeBox);
                    map.addPopup(this.popup);
                    this.popup.show();
                } else {
                    this.popup.toggle();
                }
                currentPopup = this.popup;
                OpenLayers.Event.stop(evt);
            };
            marker.events.register("mousedown", feature, markerClick);

            markers.addMarker(marker);
        }

        addLoadEvent(init);

    </script>

    <div id="map" class="smallmap"></div>

<% end %>
<% end %>

app/views/plaques/_tile.erb
<%= content_tag("div", link_to(thumbnail_img(plaque), plaque_path(plaque)), :class=>'tile') %>

app/views/plaques/create.html.erb
<p><%= pluralize (@plaques, link_to("plaque", plaques_path)) %> created</p>

app/views/plaques/edit.html.erb
<% content_for :page_title do %>Edit <%= @plaque.title %><% end %>

<%= render 'plaques/edit_bar', :plaque => @plaque %>

<div class="panel clearfix">
  <h1>Edit <%= link_to @plaque.title, plaque_path(@plaque) %></h1>
  <div class="info">
    <p>First added by <%= link_to @plaque.user.username, user_path(@plaque.user) if @plaque.user %> on <%= @plaque.created_at.to_s(:long) %>. <%= "Last updated: " + @plaque.updated_at.to_s(:long) + "." if @plaque.created_at != @plaque.updated_at %></p>
  </div>
  <%= form_for(@plaque) do |f| %>
    <p><b><%= f.label :notes %></b>: (these are for internal use, and aren't displayed publicly)<br>
    <%= f.text_area :notes, :class => :notes %></p>
    <p><%= f.label :is_current, "We believe this plaque currently exists" %> <%= f.check_box :is_current %></p>
    <p><%= f.submit "Save", :class => :button %></p>
  <% end %>
</div>

<div class="panel clearfix">
  <%= button_to("Delete plaque", plaque_path(@plaque.id), {:method => :delete, :class => :button}) if current_user.try(:is_admin?) %>
</div>

app/views/plaques/index.csv.erb
Number,Inscription,Erected date,Language,Colour,Location,Area,Country,Co-ordinates
<%- @plaques.each do |plaque| -%>
<%= plaque.to_csv.html_safe %>
<%- end -%>

app/views/plaques/index.poi.erb
<% @plaques.each do |plaque| %><%=  poi(plaque) %><% end %>