config/routes.rb
Openplaques::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :new, :create]

  # This site is designed to be RESTful, so most of the routes are defined here as resources.

  # These ones are related to plaques, but only in general, not a single plaque, and so use plaques as a prefix in the path. These have to be defined BEFORE the plaques resource.
  scope "/plaques" do
    resources :erected_in, :controller => :plaque_erected_years, :as => :plaque_erected_years, :only => [:index, :show]
    resource :latest, :as => :latest, :controller => :plaques_latest, :only => :show
  end

  resources :plaques do
    member do
      post 'parse_inscription'
      post 'unparse_inscription'
      post 'flickr_search'
      post 'flickr_search_all'
    end
    resource :location, :controller => :plaque_location, :only => :edit
    resource :erected, :controller => :plaque_erected, :only => :edit
    resource :colour, :controller => :plaque_colour, :only => :edit
    resource :geolocation, :controller => :plaque_geolocation, :only => :edit
    resource :inscription, :controller => :plaque_inscription, :only => :edit
    resource :description, :controller => :plaque_description, :only => [:edit, :show]
    resource :language, :controller => :plaque_language, :only => :edit
    resources :connections, :controller => "PersonalConnections", :as => :connections
    resource :photos, :controller => :plaque_photos, :only => :show
    resource :talk, :controller => :plaque_talk, :only => :create
    resources :sponsorships
  end
  # map tiles are numbered using the convention at http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
  match 'plaques/tiles/:zoom/:x/:y' => 'plaques#index', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  match 'plaques/unphotographed/tiles/:zoom/:x/:y' => 'plaques#index', :id => 'unphotographed', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }

  resources :places, :controller => :countries, :as => :countries do
    resources :plaques, :controller => :country_plaques, :only => :show
    resources :areas do
      resource :plaques, :controller => :area_plaques, :only => :show
      resource :unphotographed, :controller => :area_plaques, :id => 'unphotographed', :only => :show
#      resource :ungeolocated, :controller => :area_plaques, :id => 'ungeolocated', :only => :show
    end
  end
  resources :locations, :only => [:show, :edit, :update, :destroy]
  resources :areas, :controller => :all_areas, :only => :show
  resource :areas, :controller => :all_areas, :only => :show

  resources :photos
  resources :photographers, :as => :photographers, :only => [:create, :index, :show, :new]
  resources :licences, :only => [:index, :show]

  resources :organisations do
    resource :plaques, :controller => :organisation_plaques, :only => :show
    match 'plaques/tiles/:zoom/:x/:y' => 'organisation_plaques#show', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  end
  resources :sponsorships

  resources :verbs

  scope "/roles" do
    resources "a-z", :controller => :roles_by_index, :as => "roles_by_index", :only => [:show, :index]
  end
  resources :roles
  resources :personal_roles

  scope "/people" do
    resources "a-z", :controller => :people_by_index, :as => "people_by_index", :only => :show
    resources :born_on, :controller => :people_born_on, :as => "people_born_on", :only => [:index, :show]
    resources :died_on, :controller => :people_died_on, :as => "people_died_on", :only => [:index, :show]
    resources :born_in, :controller => :people_born_on, :as => "people_born_in", :only => [:index, :show]
    resources :died_in, :controller => :people_died_on, :as => "people_died_in", :only => [:index, :show]
    resources :alive_in, :controller => :people_alive_in, :as => "people_alive_in", :only => [:index, :show]
  end
  resources :people do
    resource :plaques, :controller => :person_plaques, :only => :show
    resource :roles, :controller => :person_roles, :only => :show
  end

  resources :languages
  resources :colours
  resources :series
  resources :todo
  resources :picks

  # Convenience paths for search:
  match 'search' => "search#index"
  match 'search/:phrase' => "search#index"
  match 'match' => "match#index"

  # Convenience resources for important pages:
  resources :pages
  resource :about, :controller => :pages, :id => "about", :only => :show
  resource :contact, :controller => :pages, :id => "contact", :only => :show
  scope "/about" do
    resource :data, :controller => :pages, :id => "data", :as => "about_the_data", :only => :show
  end
  resource :contribute, :controller => :pages, :id => "contribute", :as => "contribute", :only => :show
  resource :explore, :controller => :explore, :only => :show

  # Convenience paths for login/logout/register:
  match 'logout' => 'sesssions#destroy', :as => :logout
  match 'login' => 'sesssions#new', :as => :login
  match 'register' => 'users#new', :as => :register

  # The Homepage
  root :to => "homepage#index"

  match '*path', :to => 'errors#not_found'

end

app/models/colour.rb
# This class represents 'colours', as commonly identified as the main colour on commemorative
# plaques.
# === Attributes
# * +name+ - the colour's common name (eg 'blue').
# * +slug+ - An textual identifier for the colour, usually equivalent to its name in lower case, with spaces replaced by underscores. Used in URLs.
#
# === Associations
# * Plaques - plaques which use this colour.
class Colour < ActiveRecord::Base

  before_validation :make_slug_not_war
  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug

  has_many :plaques

  scope :common, where(:common => true)
  scope :uncommon, where(:common => false)

  include ApplicationHelper

  def to_param
    slug
  end
  
  def to_s
    name
  end

end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController

  before_filter :authenticate_admin!, :only => :destroy
  before_filter :authenticate_user!, :except => [:index, :show]

  before_filter :find_colour, :only => [:edit, :update]

  def index
    @colours = Colour.all
    respond_to do |format|
      format.html
      format.kml { render "plaques/index"}
      format.osm { render "plaques/index"}
      format.xml { render :xml => @colours }
      format.json { render :json => @colours }
    end
  end

  def show
    begin
      @colour = Colour.find_by_slug!(params[:id])
    rescue
      @colour = Colour.find(params[:id])
      redirect_to(colour_url(@colour.name), :status => :moved_permanently) and return
    end

    @plaques = @colour.plaques.includes(:personal_connections => :person, :location => [:area => :country]).paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html
      format.kml { render "plaques/index" }
      format.osm { render "plaques/index" }
      format.xml  { render :xml => @colour }
      format.json { render :json => @colour }
    end
  end

  def new
    @colour = Colour.new
  end

  def create
    @colour = Colour.new(params[:colour])

    if @colour.save
      redirect_to colour_path(@colour.slug)
    else
      render :new
    end
  end

  def update
    old_slug = @colour.slug

    if @colour.update_attributes(params[:colour])
      redirect_to colour_path(@colour.slug)
    else
      @colour.slug = old_slug
      render :edit
    end
  end

  protected

    def find_colour
      @colour = Colour.find_by_slug!(params[:id])
    end

end

app/helpers/colours_helper.rb
module ColoursHelper

  def link_to_colour(colour, options = {})
    link_to(colour.name, colour_path(colour))
  end

  # Overrides the default generated named path with one that uses the colour's name
  # (eg 'blue') as its identifier rather than its numerical ID.
  def colour_path(colour, options = {})
    url_for(options.merge(:controller => :colours, :action => :show, :id => colour.slug))
  end

  def colour_url(colour, options = {})
    colour_path(colour, options.merge(:only_path => false))
  end

end

app/views/colours/_colour.html.erb
<%= colour.to_s %>

app/views/colours/edit.html.erb
<% @page_title = "Rename '" + @colour.name + "'" %>
<% content_for :page_title, @page_title %>
<h1><%= @page_title %></h1>

<%= form_for @colour, :url => colour_path(@colour) do |colour| %>
	<%= colour.label :name, "Name" %>
	<%= colour.text_field :name %>

	<div>
		<%= colour.label :slug, "URL slug (lowercase and underscores only)" %>
		<%= colour.text_field :slug %>
	</div>

	<p>
		<%= colour.label :dbpedia_uri %>
		<%= colour.text_field :dbpedia_uri %>
	</p>	
	
	<%= colour.label :common, "Common colour?" %>
	<%= colour.check_box :common %>
	
	
	<%= colour.submit "Save" %>
<% end %>

app/views/colours/index.html.erb
<% content_for :page_title, "Historical plaques - by colour" %>

<div class="panel">
  <% if current_user && current_user.is_admin? %>
    <section class="admin_panel">
      <%= link_to("Add new colour", new_colour_path(), {:class => :edit, :title => "Add new colour"}) %>
    </section>
  <% end %>
  
  <h1>Colours</h1>

  <canvas id="myCanvas" width="600" height="650">
	<ul>
      <% @colours.each do |colour| %>
        <li><%= colour %> - <%= pluralize(colour.plaques.size, "plaque") %></li>
      <% end %>
    </ul>
  </canvas>
</div>

<script>
    window.onload = function ()
    {
        var data = [<% @colours.sort{|a,b| b.plaques.size <=> a.plaques.size}.each do |colour| %><%= colour.plaques.size %>,<% end %>];
        var hbar = new RGraph.HBar('myCanvas', data);
        hbar.Set('chart.labels', [<% @colours.sort{|a,b| b.plaques.size <=> a.plaques.size}.each do |colour| %>'<%= colour %>',<% end %>]);
        hbar.Set('chart.colors', [<% @colours.sort{|a,b| b.plaques.size <=> a.plaques.size}.each do |colour| %>'<%= colour %>',<% end %>]);

        hbar.Set('chart.strokestyle', 'rgba(0,0,0,0)');
        hbar.Set('chart.labels.above', true);
        hbar.Set('chart.labels.above', true);
        hbar.Set('chart.vmargin', 15);
        hbar.Set('chart.background.grid', false);
        
        hbar.Set('chart.colors.sequential', true);

        hbar.Set('chart.xlabels', false);
        hbar.Set('chart.gutter.left', 100);
        hbar.Set('chart.gutter.right', 50);
        hbar.Set('chart.gutter.top', 25);

		hbar.Set('chart.noxaxis', true);
		hbar.Set('chart.noxtickmarks', true);
		hbar.Set('chart.noytickmarks', true);
        RGraph.isOld() ? hbar.Draw() : RGraph.Effects.HBar.Grow(hbar);
    }
</script>

app/views/colours/new.html.erb
<% content_for :page_title, "Add a plaque colour" %>

<div class="panel">
  <h1>Add colour</h1>

  <%= form_for @colour do |colour| %>
    <%= colour.label :name, "Name" %>
    <%= colour.text_field :name %>

    <p>
      <%= colour.label :dbpedia_uri %>
      <%= colour.text_field :dbpedia_uri %>
    </p>

    <%= colour.submit "Save" %>
  <% end %>
</div>

app/views/colours/show.html.erb
<% content_for :page_title, @colour.name.capitalize + " plaques" %>

<div class="panel clearfix">
  <h1><%= @colour.to_s.capitalize %> plaques</h1>
</div>

<%= will_paginate @plaques %>
<%= list(@plaques) %>
<%= will_paginate @plaques %>