config/routes.rb
Openplaques::Application.routes.draw do

  devise_for :users
  resources :users, :only => [:index, :show, :new, :create]

  # This site is designed to be RESTful, so most of the routes are defined here as resources.

  # These ones are related to plaques, but only in general, not a single plaque, and so use plaques as a prefix in the path. These have to be defined BEFORE the plaques resource.
  scope "/plaques" do
    resources :erected_in, :controller => :plaque_erected_years, :as => :plaque_erected_years, :only => [:index, :show]
    resource :latest, :as => :latest, :controller => :plaques_latest, :only => :show
  end

  resources :plaques do
    member do
      post 'parse_inscription'
      post 'unparse_inscription'
      post 'flickr_search'
      post 'flickr_search_all'
    end
    resource :location, :controller => :plaque_location, :only => :edit
    resource :erected, :controller => :plaque_erected, :only => :edit
    resource :colour, :controller => :plaque_colour, :only => :edit
    resource :geolocation, :controller => :plaque_geolocation, :only => :edit
    resource :inscription, :controller => :plaque_inscription, :only => :edit
    resource :description, :controller => :plaque_description, :only => [:edit, :show]
    resource :language, :controller => :plaque_language, :only => :edit
    resources :connections, :controller => "PersonalConnections", :as => :connections
    resource :photos, :controller => :plaque_photos, :only => :show
    resource :talk, :controller => :plaque_talk, :only => :create
    resources :sponsorships
  end
  # map tiles are numbered using the convention at http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
  match 'plaques/tiles/:zoom/:x/:y' => 'plaques#index', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  match 'plaques/unphotographed/tiles/:zoom/:x/:y' => 'plaques#index', :id => 'unphotographed', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }

  resources :places, :controller => :countries, :as => :countries do
    resources :plaques, :controller => :country_plaques, :only => :show
    resources :areas do
      resource :plaques, :controller => :area_plaques, :only => :show
      resource :unphotographed, :controller => :area_plaques, :id => 'unphotographed', :only => :show
#      resource :ungeolocated, :controller => :area_plaques, :id => 'ungeolocated', :only => :show
    end
  end
  resources :locations, :only => [:show, :edit, :update, :destroy]
  resources :areas, :controller => :all_areas, :only => :show
  resource :areas, :controller => :all_areas, :only => :show

  resources :photos
  resources :photographers, :as => :photographers, :only => [:create, :index, :show, :new]
  resources :licences, :only => [:index, :show]

  resources :organisations do
    resource :plaques, :controller => :organisation_plaques, :only => :show
    match 'plaques/tiles/:zoom/:x/:y' => 'organisation_plaques#show', :constraints => { :zoom => /\d{2}/, :x => /\d+/, :y => /\d+/ }
  end
  resources :sponsorships

  resources :verbs

  scope "/roles" do
    resources "a-z", :controller => :roles_by_index, :as => "roles_by_index", :only => [:show, :index]
  end
  resources :roles
  resources :personal_roles

  scope "/people" do
    resources "a-z", :controller => :people_by_index, :as => "people_by_index", :only => :show
    resources :born_on, :controller => :people_born_on, :as => "people_born_on", :only => [:index, :show]
    resources :died_on, :controller => :people_died_on, :as => "people_died_on", :only => [:index, :show]
    resources :born_in, :controller => :people_born_on, :as => "people_born_in", :only => [:index, :show]
    resources :died_in, :controller => :people_died_on, :as => "people_died_in", :only => [:index, :show]
    resources :alive_in, :controller => :people_alive_in, :as => "people_alive_in", :only => [:index, :show]
  end
  resources :people do
    resource :plaques, :controller => :person_plaques, :only => :show
    resource :roles, :controller => :person_roles, :only => :show
  end

  resources :languages
  resources :colours
  resources :series
  resources :todo
  resources :picks

  # Convenience paths for search:
  match 'search' => "search#index"
  match 'search/:phrase' => "search#index"
  match 'match' => "match#index"

  # Convenience resources for important pages:
  resources :pages
  resource :about, :controller => :pages, :id => "about", :only => :show
  resource :contact, :controller => :pages, :id => "contact", :only => :show
  scope "/about" do
    resource :data, :controller => :pages, :id => "data", :as => "about_the_data", :only => :show
  end
  resource :contribute, :controller => :pages, :id => "contribute", :as => "contribute", :only => :show
  resource :explore, :controller => :explore, :only => :show

  # Convenience paths for login/logout/register:
  match 'logout' => 'sesssions#destroy', :as => :logout
  match 'login' => 'sesssions#new', :as => :login
  match 'register' => 'users#new', :as => :register

  # The Homepage
  root :to => "homepage#index"

  match '*path', :to => 'errors#not_found'

end

app/controllers/plaque_photos_controller.rb
class PlaquePhotosController < ApplicationController

  before_filter :find_plaque
  respond_to :json

  def show
  	respond_to do |format|
      format.html {
      	render 'plaques/photos/show'
      }
      format.json {
        render :json => @plaque.photos.as_json
      }
    end
  end

  protected

    def find_plaque
      @plaque = Plaque.find(params[:plaque_id])
    end

end

app/views/plaque_photos/show.html.erb
<% content_for :page_title, "Photos of the " + @plaque.title %>

<%= render 'plaques/edit_bar', :plaque => @plaque %>

<div class="panel clearfix">
  <section id="photos" class="inside_panel">
    <h2>Photos of the <%= link_to(@plaque.title, @plaque) %></h2>
    <% if @plaque.photos.size < 1 %>
      <p>We don't have a photo of this plaque yet. You could be the first!</p>
    <% else %>
      <p>We display multiple photos of each plaque, so you don&apos;t have to be the first.<p>
    <% end %>
    <p>We like close-ups as well as long-shots that set the scene. The closest shot will be used as the main image so that people can read the words.</p>
    <%= content_tag("ul", :class => "photographer_photos clearfix") do %>
      <% @plaque.photos.detail_order.each_with_index do |photo, i| %>
        <li <% if i==0 %>class="primary"<% end %>>
          <% if current_user && current_user.is_admin? %>
            <section class="admin_panel">
              <%= link_to("Edit", edit_photo_path(photo), {:class => :edit, :title => "edit photo"}) %>
            </section>
          <% end %>
          <%= link_to(thumbnail_img(photo), photo.url, :class => 'photographer_thumb') %>
          <span>This <%= photo.shot_name %> was taken by <%= link_to photo.photographer, photographer_url(photo.photographer.gsub(".","_").gsub("/","_")) if photo.photographer rescue photo.photographer %></span><br/>
          <%= form_for photo do |f| %>
            <p>This is a <%= f.collection_select :shot, Photo.shots, :to_s, :to_s, :include_blank => true %> shot</p>
            <%= f.submit "Save", :class => "button" %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </section>

  <section id="where_do_they_come_from" class="inside_panel">
	  <h2>Where do these photos come from?</h2>
    <p>We don&apos;t store photos ourselves, we only link to them. Open plaques connects and adds context to existing resources on the web instead of trying to own it all ourselves.
	We use stable, open sources namely <a href="http://www.flickr.com/">Flickr</a>, <a href="http://commons.wikimedia.org/">Wikimedia Commons</a> and <a href="http://www.geograph.org.uk/">Geograph</a>.
    All the images are <a href="http://creativecommons.org/">Creative Commons</a> licenced and as such we attribute them to the copyright holder.</p>
  </section>

  <section id="using_geograph" class="inside_panel">
    <p><img src="http://www.geograph.org.uk/templates/basic/img/logo.gif"/></p>
    <h2>I found a photo of this plaque on Geograph...</h2>
    <p>
    <% @photo = Photo.new %>
    <%= form_for @photo do |f| %>
      <%= f.label(:url, "The photo page url is") %> <%= f.text_field :url %>
      <%= f.hidden_field :plaque_id, :value => @plaque.id %> Please
      <%= submit_tag("Add it", :class=>'button secondary_button') %> to Open Plaques
    <% end %>
    </p>
  </section>

  <section id="using_wikimedia" class="inside_panel">
    <p><img src="http://upload.wikimedia.org/wikipedia/commons/7/79/Wiki-commons.png"/></p>
    <h2>I found, or would like to add, a photo of this plaque on Wikimedia Commons...</h2>
    <p>A great place to donate your image to the world is <a href="http://commons.wikimedia.org/">Wikimedia Commons</a>.
	It is free, fairly easy to use, and your image will [probably] live forever as part of the awesome Wikipedia platform.
	When you are done, paste the url of the Wikimedia page in here and Open Plaques will link to the photo.</p>
    <p>
    <% @photo = Photo.new %>
    <%= form_for @photo do |f| %>
      <%= f.label(:url, "The Wikimedia photo page url is") %> <%= f.text_field :url %>
      <%= f.hidden_field :plaque_id, :value => @plaque.id %>
      <%= submit_tag("Add it", :class=>'button secondary_button') %>
    <% end %>
    </p>
  </section>
  
  <section id="how_to_add_photo" class="inside_panel">
    <h2>I'd like to add my photo via Flickr</h2>
    <ol><li>put it on <a href="http://www.flickr.com/" target="new">Flickr</a> (for free)</li>
    <li>give it a Creative Commons licence</li>
    <li>tag it <strong><%= @plaque.machine_tag %></strong></li>
    <li>add it to <a href="http://www.flickr.com/groups/openplaques/" target="new">our Flickr group</a></li>
    <li>wait 5 minutes</li>
    <li>it should now appear in the Flickr search of <a href="http://www.flickr.com/search/?q=<%= @plaque.machine_tag %>&m=machinetags&l=cc&content_type=1" target="new">photos tagged '<%= @plaque.machine_tag %>'</a></li>
    <li>wait for 24 hours and our servers should automatically find it and display it on our site</li>
    </ol>
    <br/>
    <h2>I did that, but my photo hasn&apos;t appeared!</h2>
    <p>Paste the url of the photo here and we will try to sort it out <%= form_tag("/photographers", :method => "create") do %>
      <%= label_tag(:flickr_url, "Flickr photo url:") %>
      <%= text_field_tag(:flickr_url) %>
      <%= submit_tag("Search", :class=>'button secondary_button') %>
    <% end %></p>
    <br/>
    <h2>Nope, still not working</h2>
    <ol><li>still not there?</li>
	<li>Does your photo appear in the Flickr search of <a href="http://www.flickr.com/search/?q=<%= @plaque.machine_tag %>&m=machinetags&l=cc&content_type=1" target="new">photos tagged '<%= @plaque.machine_tag %>'</a>?</li>
    <li>if not, check that the licence is Creative Commons, i.e. it shouldn&apos;t say "All Rights Reserved"</li>
    <li>also, ensure that you haven&apos;t ticked the &apos;hidden from search&apos; setting. (On Flickr, go to your profile by clicking your username in top right hand corner, do you have "Hide your stuff from public searches" set to "no"?)</li>
    <li>a brand new Flickr account might not be included in their search immediately. Sometimes it waits until you have posted 5+ images. Enter your photo&apos;s url into the box below and we'll see what we can do...</li>
    <li>you can try <%= button_to "giving the automatic search a kick", :controller => :plaques, :action => :flickr_search, :id => @plaque, :class => "button secondary_button" %></li></ol>
  </section>
  
  <section id="help_photos" class="inside_panel">
    <h2>Help, I really don&apos;t understand!</h2>
    <p>If this all proves too complicated, then have a chat with us via email. We are generally rather nice and want to help. You can <a href="http://openplaques.org/contact">email your photo</a> to us stating that you are happy for us to publish it as open data on your behalf and that you grant anyone in the world the right to re-use the image.</p>
  </section>

</div>